baseURL:
disableKinds: [section, taxonomy, term, RSS, sitemap, 404]
enableRobotsTXT: true
languageCode: en

title: Resume
theme: test

params:
  open: true                # open or close your site
  dateFormat: 2006-01-02    # date format
  themeColor: '#1DA1F2'     # your favorite theme color
  allowSearchEngines: true  # allow search engines indexing your resume
  analytics:
    google:                 # your google analytics
    cloudflare:             # your cloudflare analytics
  experience:
    enable: true
  skills:
    enable: true
  contact:
    enable: true
  education:
    enable: true
