baseurl: 'http://example.org/'
languageCode: en-us
title: Resume
theme: orbit
googleAnalytics: UA-XXXXXXX-Y
disableRSS: true
disableSitemap: true
disable404: true
params:
  description: Hugo Responsive Resume/CV Theme for Developers
  author: Pavel Kanyshev
  styles: styles-6.css
  profile:
    name: John Doe
    tagline: Software Developer
    #avatar: profile.png
  contact:
    enable: true
    list:
      # - class: email
      #   icon: fa-envelope
      #   url: 'mailto: yourname@email.com'
      #   title: john.doe@website.com
      # - class: phone
      #   icon: fa-phone
      #   url: 'tel:+1234567890'
      #   title: '+1234567890'
      - class: website
        icon: fa-globe
        url: //portfoliosite.com
        title: portfoliosite.com
      - class: linkedin
        icon: fa-linkedin
        url: //linkedin.com/in/msguerri
        title: msguerri
      - class: github
        icon: fa-github
        url: //github.com/mrsguerri
        title: mrsguerri
      # - class: twitter
      #   icon: fa-twitter
      #   url: //twitter.com/username
      #   title: '@twittername'
  education:
    enable: true
    title: Education
    list:
      - degree: BSc in Computer Science
        college: California State University, Long Beach
        dates: 2007 - 2011
  language:
    enable: true
    title: Languages
    list:
      - language: English
        level: Native
      - language: Italian
        level: Native
  # interests:
  #   enable: true
  #   title: Interests
  #   list:
  #     - interest: Climbing
  #     - interest: Snowboarding
  #     - interest: Cooking
  # summary:
  #   enable: true
  #   icon: fa-user
  #   title: Career Profile
  #   summary: >-
  #     **Summarise your career here** lorem ipsum dolor sit amet, consectetuer
  #     adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
  #     Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque
  #     penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec
  #     quam felis, ultricies nec, pellentesque eu.
  experiences:
    enable: true
    icon: fa-briefcase
    title: Experiences
  jobs:
    list:
      - position: Lead Developer
        dates: 2015 - Present
        company: 'Startup Hubs, San Francisco'
        details: >-
          **Describe your role here** lorem ipsum dolor sit amet, consectetuer
          adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum
          sociis natoque penatibus et magnis dis parturient montes, nascetur
          ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu,
          pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.

           Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
      - position: Senior Software Engineer
        dates: 2014 - 2015
        company: 'Google, London'
        details: >-
          **Describe your role here** lorem ipsum dolor sit amet, consectetuer
          adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum
          sociis natoque penatibus et magnis dis parturient montes, nascetur
          ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu,
          pretium quis, sem.
      - position: UI Developer
        dates: 2012 - 2014
        company: 'Amazon, London'
        details: >-
          **Describe your role here** lorem ipsum dolor sit amet, consectetuer
          adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum
          sociis natoque penatibus et magnis dis parturient montes, nascetur
          ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu,
          pretium quis, sem.
  projects:
    enable: true
    icon: fa-archive
    title: Projects
    intro: >-
      **You can list your side projects or open source libraries in this
      section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Vestibulum et ligula in nunc bibendum fringilla a eu lectus
    list:
      - title: Hugrid
        url: 'https://github.com/aerohub/hugrid'
        tagline: >-
          Grid theme for Hugo. It's a kind of boilerplate to perform anyone or
          anything quickly. Portfolio, collection, bookmarks, contacts and so on
      - title: Simple FAQ Theme for Hugo
        url: 'https://github.com/aerohub/hugo-faq-theme'
        tagline: >-
          Simple FAQ Theme for Hugo. You may use this theme for building very
          simple FAQs or note lists.
      - title: Hugo Identity
        url: 'https://github.com/aerohub/hugo-identity-theme'
        tagline: Little profile/card-style template for Hugo.
      - title: Orbit
        url: 'https://github.com/aerohub/hugo-orbit-theme'
        tagline: Hugo Resume/CV Theme for Developers.
      - title: Me
        url: 'https://github.com/aerohub/hugo-me-theme'
        tagline: A simple responsive Hugo theme for personal site.
  skills:
    enable: true
    icon: fa-rocket
    title: Skills & Proficiency
    list:
      - skill: Python & Django
        level: 98%
      - skill: Javascript & jQuery
        level: 98%
      - skill: Angular
        level: 95%
      - skill: HTML5 & CSS
        level: 95%
  footer:
    copyright: 'Matt Sguerri'
